# Build executable takes around 13m
name: Build

on:
  # push:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11.9"
      #     architecture: "x64"
      #     cache: "pip"
      #     cache-dependency-path: |
      #       **/requirements*.txt

      # - name: Install Dependencies
      #   run: |
      #     pip install -r requirements.txt

      # - name: Build Executable
      #   uses: Nuitka/Nuitka-Action@main
      #   with:
      #     nuitka-version: main
      #     script-name: generate.py

      - name: Copy Datafiles
        run: |
          mkdir "${GITHUB_WORKSPACE}/build"
          cp -R data "${GITHUB_WORKSPACE}/build/"
          cp -R .readme "${GITHUB_WORKSPACE}/build/"
          cp README.md "${GITHUB_WORKSPACE}/build/"

      - name: Create Archive
        run: |
          7z a "generate-${{ matrix.os }}.7z" "${GITHUB_WORKSPACE}/build/*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            *.7z
          # build/*.exe
          # build/*.bin
          # build/*.app/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare Artifacts
      id: prepare_artifacts
      run: |
        tag="${GITHUB_REF#refs/*/}"
        echo "current_tag=${tag}" >> $GITHUB_OUTPUT
        mkdir -p "${GITHUB_WORKSPACE}"/release
        find "${GITHUB_WORKSPACE}"/artifacts/ -name "*.7z" | while read f ; do
          p="$(basename "$f")"
          cp -v "$f" "${GITHUB_WORKSPACE}/release/generate-${GITHUB_REF#refs/*/}-${p#generate-}"
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Generate Plus ${{ steps.prepare_artifacts.outputs.current_tag }}
        draft: true
        prerelease: false
        files: release/generate-*.7z