name: Build

on:
  # push:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: generate.py

      - name: Copy Datafiles
        run: |
          cp -R data "${GITHUB_WORKSPACE}/build/"
          cp README.md "${GITHUB_WORKSPACE}/build/"

      - name: Create Archive
        run: |
          7z a "generate-${{ matrix.os }}.7z" ./build/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.7z
          # build/*.exe
          # build/*.bin
          # build/*.app/**/*
